# Generated by Django 5.0.3 on 2024-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_blogpost_author"),
    ]

    operations = []
