# Generated by Django 5.0.3 on 2024-07-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20240704_1849"),
        ("api", "0004_add_updated_at"),
    ]

    operations = []
