# Generated by Django 5.0.6 on 2024-07-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_0003_auto_20240704_1849_0004_add_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-published"]},
        ),
    ]
